CONFIG_USE_SEGGER_RTT=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_BME680=y

CONFIG_CHIP_NFC_ONBOARDING_PAYLOAD=n

CONFIG_NCS_SAMPLE_MATTER_WATCHDOG=y

CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_NCS_SAMPLE_MATTER_USE_DEFAULT_BUTTON_HANDLER=n
